### ISSUE TITLE
Close div tag on responsive card example

### ISSUE THREAD

**Issue by kookster** [PRX/Play-Next.js#109]
https://github.com/PRX/Play-Next.js/blob/main/pages/index.tsx#L294

Should be `</div>`

**Comment by IcusFMagni** [comment]
Hey @a-maci29 I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/everything-55ca3fa462aa9cc8628c6839/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_
