### ISSUE TITLE
Create "preview" route for use in app like Feeder

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/Play-Next.js#122]
Having a route dedicated to configuration preview in our apps will allow for more flexibility to adjust behavior and caching to fit expectations in those apps, without affecting and adding complexity to public use embeds.

**Comment by cavis** [comment]
Two use cases here:

1. The episode isn't published yet.  So we're passing in query params for pretty much everything, and a temporary dovetail mp3 url containing your user's token.
2. The episode is published (in the public RSS).  Any changes you make to episode metadata/files are going to take awhile to process, reach S3, and break through the CloudFront cache(s) behind the public feed url.
