### ISSUE TITLE
Add support for changing playback speed

### ISSUE THREAD

**Issue by kookster** [PRX/Play-Next.js#140]
Had some folks ask about this, as it is becoming a more common feature of audio players, even the html audio element controls:

https://revealnews.org/podcast/cashing-in-on-troubled-teens-update-2024/

**Comment by rpeterman-gp** [comment]
I think this issue will be a good place to implement a User Preferences menu to provide controls for this and other aspects of the player (volume, theme, CC options).

**Comment by rpeterman-gp** [comment]
@brandonhundt @kookster What speed options do we want to provide? Steps of 0.25 from 0.25 - 2 like that audio element (at least in Chrome)? Our current playback speed shortcut toggles between 1 and 3. I was thinking:

- 0.25
- 0.5
- 0.75
- 1 (Normal)
- 1.5
- 2
- 3

**Comment by kookster** [comment]
I don't see many slower than 1x options on other players. Apple offers .75x, same with Overcast
