### ISSUE TITLE
Better error handling and messaging for embeds using bad feed URL's

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/Play-Next.js#86]
We are seeing a lot of embed requests using feed URL's are inaccessible (404, Bad DNS, SSL issues, etc.). These embeds were probably already broken with the Angular player, but those requests were happening on the client, so I am not sure if we were aware of those error (New Relic?)

Right now we are just throwing an error when fetching of RSS feed fails, which just ends up showing a generic error message. We should probably handle these errors a little better, and present something a bit more informative to the user viewing the embed.

**Comment by farski** [comment]
All feeds in the old player were proxied through the proxy server, which bubbled up any errors it ran into, so we were able to monitor those at the server and load balancer. One of the benefits of having the proxy server and front end server was that we could monitor them separately, so we had tuned the proxy alarms to ignore a background noise level of proxy errors.

It would alarm on 15 errors in 1 minute, or 5 errors in 3-out-of-10 minutes.
